name: Baseline Check

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  baseline:
    permissions:
      contents: read
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/baseline-check.yml@daa74f7c13e04bc77109021922e3fcaa9644b75c # main
    with:
      has-docker: false
