name: Baseline Check

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  baseline:
    permissions:
      contents: read
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/baseline-check.yml@8e713c7c8867caa653483a934e2b74a62e31fc0b # main
    with:
      has-docker: false
