name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/python-release.yml@eeced1217f95cc04e514102571282a2ff2d1e3f1 # main
    with:
      github-release: true
