name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    permissions:
      id-token: write
    uses: damien-robotsix/robotsix-mill/.github/workflows/python-release.yml@main
    secrets: inherit
